name: bozpy
version: 1
accesskey: 4m5j13nn35
worker: gevent
libraries:
- name: gevent
  version: "1.0rc2"
- name: jinja2
  version: "2.6"
- name: MySQLdb
  version: "1.2.3"
- name: misaka
  version: "1.0.2"
handlers:
- url: /static/
  static_path: static
  gzip: on
- url: /favicon.ico
  static_path: favicon.ico
  gzip: on
